# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remarks')),
            ],
            options={
                'db_table': 'sales_order',
                'permissions': (('view_sales_order', 'Can view sales order'),),
            },
        ),
        migrations.CreateModel(
            name='SalesOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Unit Price')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.SalesOrder')),
            ],
            options={
                'db_table': 'sales_order_details',
            },
        ),
    ]
