# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'permissions': (('view_salesorder', 'Can view sales order'),)},
        ),
    ]
