# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20170505_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_name',
            field=models.CharField(default='default', max_length=100, verbose_name='Customer Name'),
            preserve_default=False,
        ),
    ]
