# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 08:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupation')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('refer_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Refered By')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('office_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Office Address')),
                ('delivery_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Delivery Address')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='At')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.Profile')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20, verbose_name='Item Code')),
                ('name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='At')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.Profile')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_code', models.CharField(max_length=100, verbose_name='External Code')),
                ('internal_code', models.CharField(max_length=100, verbose_name='Internal Code')),
                ('unit', models.CharField(default='yard', max_length=50, verbose_name='Unit')),
                ('reference_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Reference Price')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='At')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.Profile')),
            ],
            options={
                'db_table': 'item_material',
            },
        ),
        migrations.CreateModel(
            name='ItemQualityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='At')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.Profile')),
            ],
            options={
                'db_table': 'item_quality_type',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='At')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_payments', to='profiles.Profile')),
            ],
            options={
                'db_table': 'item_type',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, verbose_name='Order Id')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='Order Date')),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remarks')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='At')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.Profile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='pursuit.Customer')),
                ('sales_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='profiles.Profile')),
            ],
            options={
                'db_table': 'sales_order',
                'permissions': (('view_salesorder', 'Can view sales order'),),
            },
        ),
        migrations.CreateModel(
            name='SalesOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.IntegerField(verbose_name='Row No')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('promotion_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Promotion Price')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='At')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.Profile')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_details', to='pursuit.SalesOrder')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_details', to='pursuit.ItemMaterial')),
            ],
            options={
                'db_table': 'sales_order_detail',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=datetime.date.today, verbose_name='Payment Date')),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remarks')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction Id')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='At')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.Profile')),
            ],
            options={
                'db_table': 'sales_order_payment',
            },
        ),
        migrations.AddField(
            model_name='itemmaterial',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_materials', to='pursuit.ItemQualityType'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='pursuit.ItemType'),
        ),
    ]
