# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pursuit', '0002_auto_20170514_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='order_id',
            field=models.CharField(default=None, max_length=20, unique=True, verbose_name='Order Id'),
        ),
    ]
