# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pursuit', '0003_auto_20170515_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdDistributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20, unique=True, verbose_name='Prefix')),
                ('last_id', models.IntegerField(verbose_name='Last Id')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='At')),
            ],
            options={
                'db_table': 'id_distributor',
            },
        ),
    ]
